### PR TITLE
Turn down logging level for SASL authentication attempts

### LINKED ISSUE #136: Excessive logging with SASL-enabled memcached servers
Logging an informational alert for every single connection attempt to SASL-enabled memcached instances results in extremely high log volumes in my environment.

As these messages only track normal, expected behavior, I consider this to be useful only for troubleshooting a broken configuration or otherwise bad behavior. This should be logged to `DEBUG` level.

### PR DESCRIPTION
**Pull request by ajwood-acquia**
Fixes #136

---
This change is [Reviewable](https://reviewable.io/reviews/jaysonsantos/python-binary-memcached/137)

### CODE REVIEW

**Comment by jaysonsantos** [comment]
Thanks @ajwood-acquia !

**Comment by ajwood-acquia** [comment]
@jaysonsantos no problem at all, thanks for the quick response!

Any idea when you're planning to cut the next release tag for this project?

**Comment by jaysonsantos** [comment]
Hey there, I will do it now so you can already get the change.

**Comment by ajwood-acquia** [comment]
awesome, thanks :D

**Pull request merged**
