### PR TITLE
Add 'raw' and 'compress' options; replace pickle with JSON

### PR DESCRIPTION
**Pull request by hathawsh**
This proposed change combines two enhancements. If you would like me to separate them, I would be happy to do so.

1) Added 'raw' and 'compress' parameters to the get and set methods.

It's currently difficult to store binary strings using this package in Python 3. (I'm caching images.) This pull request fixes that by adding an optional 'raw' bool parameter to the get() methods. The 'raw' parameter, when true, causes the client class to skip decoding and just return bytes.

I also added a 'compress' option to the set() family of methods. When 'compress' is false, it disables compression of things that don't make sense to compress, such as images (which are already compressed.)

I added tests and fixed a test that was failing on Python 3.5.2.

2) Replaced pickle with JSON as the default object serialization mechanism.

Python pickles are, sadly, dangerously insecure. The act of unpickling can execute arbitrary code. The pickle machinery is also significantly slower than most of the available Python JSON modules.

This proposed patch changes the default serialization mechanism used by this package from pickle to JSON. It is still possible to revert to pickle serialization, as proven by some unit tests I added.

---

This change is [Reviewable](https://reviewable.io/reviews/jaysonsantos/python-binary-memcached/57)

### CODE REVIEW

**Comment by jaysonsantos** [comment]
Hey, sorry for the long time. I saw that this will break the api of memcached, did you see this api in any memcached library? What happend when you tried to set binary data there? To change pickle to json we would need a minor version increased (which basically means a major as this is not 1.0).
How would you serialize objects, setting the serializer for pickle? Did they also remove it?
I am doing a slow review because I have some personal stuff to solve but I will get there :).
And thanks for your PR!

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bmemcached/client.py, line 98 at r1](https://reviewable.io:443/reviews/jaysonsantos/python-binary-memcached/57#-KTLG4uxBwlTD5f1WlP6:-KTLG4uxBwlTD5f1WlP7:bkkfocx) ([raw file](https://github.com/jaysonsantos/python-binary-memcached/blob/0c90cf81bc2870e19199552a2234b748ed38b6c4/bmemcached/client.py#L98)):*
> ```Python
> 
>         :param key: Key's name
>         :type key: str
> ```

Why not using six.string_type, assuming that it is str is wrong because in python3 it will be converted to bytes in the end if str is sent but nothing would happen if bytes is sent.

---

*[bmemcached/client.py, line 159 at r1](https://reviewable.io:443/reviews/jaysonsantos/python-binary-memcached/57#-KTLH5D_coGeKFkeZpW-:-KTLH5D_coGeKFkeZpW0:b-ynqt6b) ([raw file](https://github.com/jaysonsantos/python-binary-memcached/blob/0c90cf81bc2870e19199552a2234b748ed38b6c4/bmemcached/client.py#L159)):*
> ```Python
>         return d
> 
>     def set(self, key, value, time=0, compress=True):
> ```

Compress is defined by the threshold [1] on pylibmc, would you mind changing? It is good because we can become more compatible with the "standard" library.
[1] http://sendapatch.se/projects/pylibmc/reference.html#pylibmc.Client.set

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jaysonsantos/python-binary-memcached/57#-:-KTLGQbaRTT8RQs3MCgi:b-jzrr0c)*

**Comment by hathawsh** [comment]
The other Python memcached libraries I've found don't appear to support caching binary data in Python 3 except through base64 encoding or similar. I chose this library because it looked like it would support binary data in Python 3 more easily than the rest.

To switch the serialization back to pickling, all you have to do is add "dumps=pickle.dumps, loads=pickle.loads" to the Client constructor call. I considered adding security warnings about pickling to the documentation, but I suggest it's better to make the module safe by default instead, with an easy way to go back. I'm glad you haven't yet released version 1.0, otherwise we would have to consider this change more carefully.

The six package doesn't have anything called string_type. :-) It does have binary_type, text_type, and string_types (plural), but as it turns out, "str" is probably what you want in Python 3 as well as Python 2.  You want the keys and values to be as natural as possible, and "str" is the most natural choice for key and value type most of the time.

Yes, I could change compress to compress_level. The value -1 probably should mean no compression.

**Comment by jaysonsantos** [comment]
Hi @hathawsh I will make a new check today and let you know to merge it. About the str type on python 2 that is a common scenario if you deal with ascii text, If you develop stuff for other countries you would use unicode a lot but that is just nitpicking.
Thanks again!

**Comment by hathawsh** [comment]
Today I fixed the 'str' type declarations and replaced the 'compress' parameters with 'compress_level' to match pylibmc, as you requested. Sorry for the delay and thanks for your patience.

**Comment by hathawsh** [comment]
OK, I'll try that out.

**Comment by hathawsh** [comment]
I added a `binary` flag and remove the `raw` parameters. I like the way it worked out.

**Comment by jaysonsantos** [comment]
Reviewed 1 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jaysonsantos/python-binary-memcached/57)*

**Comment by jaysonsantos** [comment]
Thank you very much @hathawsh. Do you need a new version on pypi?

**Comment by hathawsh** [comment]
A pypi release would be helpful. Thank you!

**Comment by zzzeek** [comment]
Hello -

dogpile.cache is completely broken for bmemcached now, and with this change, bmemcache is broken by default against the API of all the other memcached libraries, all of which use pickle, meaning, you send an instantiated class in, you get back an instance of that class.    It is fully a nice thing to support JSON serialization, but to switch the library to do that by default means complete breakage for everyone.   While it looks here like the behavior is easily reversible via a configurational setting, I don't really have the resources to maintain dogpile's backend for a project that's going to make huge breaking changes like this once in awhile, as dogpile supports a plugin architecture that would allow bmemcached to provide a dogpile backend as a setuptools entrypoint.     If bmemcached as a project is not interested in maintaining full API compatibility with the other memcached libs, that's totally fine, but if so I'm going to drop the backend from dogpile and let folks make their own backends for whichever bmemcached API they are interested in using.   See https://bitbucket.org/zzzeek/dogpile.cache/issues/108/test-failures-with-latest-binary-memcached#comment-None

**Comment by jaysonsantos** [comment]
Hey @zzzeek you are right, I only thought about the other parameter which would break the api but I forgot to think about the serialization. Thanks for the heads up, I will make it optional to be json to make it back compatible again.

**Comment by zzzeek** [comment]
OK, then once you release I can close out my bug report, thanks very much!

**Comment by hathawsh** [comment]
Sorry guys, I didn't realize anyone depended on pickling by default.  I'll be happy to help switch it back if you need me.  Meanwhile, the documentation should warn users that unpickling, a subtle security hole, is enabled by default.

**Comment by zzzeek** [comment]
it's only a security hole if an application is either a. forcing untrusted string input into memcached while somehow *bypassing* the pickle dumps step (allowing the untrusted input to itself be a malicious pickle) or b. allowing untrusted code execution in the first place where a class of untrusted source is invoked and instantiated.    The former is not real world use case and the latter is already insecure.

**Comment by hathawsh** [comment]
The main attack I'm thinking of is an intruder might first compromise some small service that accesses a central memcache server, then inject malicious pickles into memcache to gain access to other services. Yes, this attack depends on the existence of some other security hole, but defense in depth is important.

**Comment by jaysonsantos** [comment]
Hey Shane, that would be great because right now it is a bit hard to find enough time for it.
I saw that some concurrency tests on dogpile are being skipped and I will try to tackle them as their test suite is way better. In the end I chose to leave the pooling or locking to the user to avoid freezing too much what he/she wants to do. 
➢ Sorry guys, I didn't realize anyone depended on pickling by default. I'll be happy to help switch it back if you need me. Meanwhile, the documentation should warn users that unpickling, a subtle security hole, is enabled by default.

**Pull request merged**
