### PR TITLE
Return pickle as default serializer

### PR DESCRIPTION
**Pull request by jaysonsantos**
This change is [Reviewable](https://reviewable.io/reviews/jaysonsantos/python-binary-memcached/73)

### CODE REVIEW

**Comment by jaysonsantos** [comment]
This fixes #73

**Comment by jaysonsantos** [comment]
Hi @zzzeek would you mind taking a look on the api? I also tested dogpile tests + the ones of concurrency and everything seems to be working.

**Comment by zzzeek** [comment]
OK, you uncommented the ones that were failing a long time ago?   that's great.   if you release this I can look into re-enabling those tests on my end.

**Comment by jaysonsantos** [comment]
@zzzeek Yes, I removed all the skips and they seem to be working

**Comment by jaysonsantos** [comment]
@zzzeek this should be working now

**Comment by zzzeek** [comment]
confirmed this repairs normal test coverage, thanks very much!    testing out the previously skipped tests as a separate change.

**Comment by zzzeek** [comment]
still seeing a failure for the "concurrency" tests: https://jenkins.sqlalchemy.org/job/dogpile_gerrit/59/backend=memcached,pyv=py36/testReport/junit/tests.cache.test_memcached_backend/BMemcachedDistributedWithTimeoutTest/test_threaded_dogpile/ .    These tests are quite crazy so aren't that great to figure out what might be going on, unfortunately.

**Comment by jaysonsantos** [comment]
strange, they worked on a clean docker environment. I will make some changes and try to figure it out.

**Pull request merged**
